version: '3.8'
services:
  web:
    image: thinhtran3588/tqt-web-starter-kit
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    ports:
      - '3001:3001'
    volumes:
      - .:/app
